# https://github.com/srggrs/assign-one-project-github-action
name: Auto Assign to Project

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed]
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/Aegis-Nocta/projects/2'
  
    - name: Assign CLOSED issues and CLOSED pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'closed'
      with:
        project: 'https://github.com/orgs/Aegis-Nocta/projects/2'
        column_name: 'Done'
